#!/bin/sh

NUMAKE=$(readlink -f numake)

${NUMAKE} $@
while :
do
	inotifywait \
		-e close_write \
		`${NUMAKE} --sources` `find . -name '*.nu'`
	${NUMAKE} $@ && {
		echo "-------------------------------------"
		valgrind --leak-check=full bin/lip
		echo "-------------------------------------"
	}
done
