#!/bin/sh -e

`${NUMAKE} --enable-trace`
${NUMAKE} --depend ${0}

BUILD_SUBDIR=${m%%/*}
BUILD_PREFIX=${BUILD_DIR}/${BUILD_SUBDIR}
source=${2%.ninja}
source=${source#$BUILD_PREFIX/}
mkdir -p $(dirname ${2})
echo "build ${2%.ninja}.o: compile-${1} ${source}" >> $2
